export const SIGNIN_USER_REQUEST = "SIGNIN_USER_REQUEST";
export const SIGNIN_USER_SUCCESS = "SIGNIN_USER_SUCCESS";
export const SIGNIN_USER_FAILED = "SIGNIN_USER_FAILED";

export const GET_USER_REQUEST = "GET_USER_REQUEST";
export const GET_USER_SUCCESS = "GET_USER_SUCCESS";
export const GET_USER_FAILED = "GET_USER_FAILED";

export const SIGNUP_USER_REQUEST = "SIGNUP_USER_REQUEST";
export const SIGNUP_USER_SUCCESS = "SIGNUP_USER_SUCCESS";
export const SIGNUP_USER_FAILED = "SIGNUP_USER_FAILED";

export const USERNAME_CHANGE_REQUEST = "USERNAME_CHANGE_REQUEST";
export const USERNAME_CHANGE_SUCCESS = "USERNAME_CHANGE_SUCCESS";
export const USERNAME_CHANGE_FAILED = "USERNAME_CHANGE_FAILED";

export const SIGNOUT_USER = "SIGNOUT_USER";
